name: PYPI Package Deploy
on:
  push:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    strategy:
      matrix:
        python-version: [ "3.10"]

    runs-on: ubuntu-latest
    steps:
      - uses: Gr1N/setup-poetry@v7
      - name: Testing
        run: poetry run pytest
      - name: Building
        working-directory: ./
        run: ls && poetry build
      - name: Publishing to PYPI
        working-directory: ./
        run: poetry publish --user sejjax --password ${{ secrets.PYPI_PASSWORD }}
